- 
  name: Create change request
  hosts: localhost

  tasks:
    - name: Create change request
      snow_record:
        state: present
        table: change_request
        username: "admin"
        password: "GQu1rjWXcUj4"
        instance: "dev88678"
        data:
          severity: "2"
          priority: "2"
          short_description: "PET-CLI-DEP-{{ build_id }}"
          assignment_group: "CAB Approval"
          assigned_to: "cab approver"
          start_date: "2021-04-07"
          end_date: "2021-04-07"
      register: new_incident

    - debug: 
        var: new_incident.record